-- TRUNCATE ALL TABLES
-- ¡¡¡ DISABLE FOREIGN KEY CHECKS !!!
TRUNCATE TABLE brands;
TRUNCATE TABLE categories;
TRUNCATE TABLE components;
TRUNCATE TABLE measurement_units;
TRUNCATE TABLE mps;
TRUNCATE TABLE mps_periods;
TRUNCATE TABLE products;
TRUNCATE TABLE purchases;
TRUNCATE TABLE purchases_components;
TRUNCATE TABLE sales;
TRUNCATE TABLE sales_products;
TRUNCATE TABLE `sessions`;
TRUNCATE TABLE spreadsheet;
TRUNCATE TABLE users;